# Generated by Django 4.2.1 on 2023-05-18 22:48

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=order.models.gen_new_id, editable=False, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('date', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
    ]
